flags:
  generic-deriving:
    base-4-9: false
  semigroups:
    bytestring-builder: false
  time-locale-compat:
    old-locale: false
extra-package-dbs: []
packages:
- '.'
extra-deps:
- Diff-0.3.4
- HTF-0.13.1.0
- HUnit-1.5.0.0
- MissingH-1.4.0.1
- QuickCheck-2.9.2
- StateVar-1.1.0.4
- adjunctions-4.3
- aeson-1.0.2.1
- attoparsec-0.13.1.0
- base-compat-0.9.1
- base-orphans-0.5.4
- base64-bytestring-1.0.0.1
- bifunctors-5.4.1
- blaze-builder-0.4.0.2
- call-stack-0.1.0
- comonad-5
- contravariant-1.4
- cpphs-1.20.2
- distributive-0.5.0.2
- dlist-0.8.0.2
- exceptions-0.8.3
- fail-4.9.0.0
- flow-1.0.7
- free-4.12.4
- generic-deriving-1.11.1
- hashable-1.2.4.0
- haskell-src-1.0.2.0
- hslogger-1.2.10
- kan-extensions-5.0.1
- lens-4.15.1
- lifted-base-0.2.3.8
- monad-control-1.0.1.0
- mtl-2.2.1
- network-2.6.3.1
- old-locale-1.0.0.7
- old-time-1.1.0.3
- parallel-3.2.1.0
- parsec-3.1.11
- polyparse-1.12
- prelude-extras-0.4.0.3
- primitive-0.6.1.0
- profunctors-5.2
- random-1.1
- reflection-2.1.2
- regex-base-0.93.2
- regex-compat-0.95.1
- regex-posix-0.95.2
- safe-0.3.10
- scientific-0.3.4.9
- semigroupoids-5.1
- semigroups-0.18.2
- stm-2.4.4.1
- syb-0.6
- tagged-0.8.5
- text-1.2.2.1
- tf-random-0.5
- time-locale-compat-0.1.1.3
- transformers-base-0.4.4
- transformers-compat-0.5.1.4
- unordered-containers-0.2.7.1
- vector-0.11.0.0
- void-0.7.1
- xmlgen-0.6.2.1
resolver: ghc-7.10.3
