flags:
  generic-deriving:
    base-4-9: false
  semigroups:
    bytestring-builder: false
  time-locale-compat:
    old-locale: false
extra-package-dbs: []
packages:
- '.'
extra-deps:
- Diff-0.3.4
- HTF-0.13.1.0
- adjunctions-4.3
- aeson-1.0.2.1
- attoparsec-0.13.1.0
- base-compat-0.9.1
- base-orphans-0.5.4
- base64-bytestring-1.0.0.1
- bifunctors-5.4.1
- blaze-builder-0.4.0.2
- comonad-5
- contravariant-1.4
- cpphs-1.20.2
- distributive-0.5.0.2
- dlist-0.8.0.2
- exceptions-0.8.3
- fail-4.9.0.0
- flow-1.0.7
- free-4.12.4
- generic-deriving-1.11.1
- kan-extensions-5.0.1
- lens-4.15.1
- lifted-base-0.2.3.8
- monad-control-1.0.1.0
- polyparse-1.12
- prelude-extras-0.4.0.3
- profunctors-5.2
- reflection-2.1.2
- scientific-0.3.4.9
- semigroupoids-5.1
- semigroups-0.18.2
- tagged-0.8.5
- time-locale-compat-0.1.1.3
- transformers-base-0.4.4
- transformers-compat-0.5.1.4
- void-0.7.1
- xmlgen-0.6.2.1
resolver: ghc-7.10.3
