flags:
  semigroups:
    bytestring-builder: false
  time-locale-compat:
    old-locale: false
extra-package-dbs: []
packages:
- '.'
extra-deps:
- Diff-0.3.4
- HTF-0.13.1.0
- aeson-1.0.2.1
- ansi-terminal-0.6.2.3
- ansi-wl-pprint-0.6.7.3
- attoparsec-0.13.1.0
- base-compat-0.9.1
- base64-bytestring-1.0.0.1
- blaze-builder-0.4.0.2
- cpphs-1.20.2
- dlist-0.8.0.2
- extensible-exceptions-0.1.1.4
- fail-4.9.0.0
- flow-1.0.7
- hostname-1.0
- lifted-base-0.2.3.8
- monad-control-1.0.1.0
- polyparse-1.12
- scientific-0.3.4.9
- semigroups-0.18.2
- tagged-0.8.5
- time-locale-compat-0.1.1.3
- transformers-base-0.4.4
- transformers-compat-0.5.1.4
- xml-1.3.14
- xmlgen-0.6.2.1
resolver: ghc-7.10.3
